name: Terraform AWS workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "ACM"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Terraform
        run: terraform -chdir=./terraform/acm init

      - name: Plan Terraform changes
        run: terraform -chdir=./terraform/acm plan

      - name: Apply Terraform changes
        run: terraform -chdir=./terraform/acm apply

      - name: Destroy Terraform resources
        run: terraform -chdir=./terraform/acm destroy (optional)