name: Terraform AWS workflow

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "aws-resume-challenge"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "aws-resume-challenge"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "ACM"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Terraform
        run: terraform -chdir=terraform/acm init

      - name: Plan Terraform changes
        run: terraform -chdir=terraform/acm plan

      - name: Apply Terraform changes
        run: terraform -chdir=terraform/acm apply
