name: Terraform AWS workflow

on:
  push:
    branches:
      - main

env:
  TF_WORKSPACE: "aws_resume_challenge"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "ACM"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Initialize Terraform
        run: terraform -chdir=terraform/acm init

      - name: Plan Terraform changes
        run: terraform -chdir=terraform\\acm plan

      - name: Apply Terraform changes
        run: terraform -chdir=terraform\\acm apply

      - name: Destroy Terraform resources
        run: terraform -chdir=terraform\\acm destroy (optional)
